# Automatically generated by configure - do not modify!
FFMPEG_ARCH_VARIANT := $(TARGET_ARCH_VARIANT)
ifeq ($(FFMPEG_2ND_ARCH), true)
#ifndef VENDOR_EDIT
#Wuhan@PSW.MM.MediaServer.Player., 2018/09/17,
#Modify for compile error
#  FFMPEG_ARCH_VARIANT := $(TARGET_2ND_ARCH_VARIANT)
#else /* VENDOR_EDIT */
   FFMPEG_ARCH_VARIANT := armv7-a-neon
#endif /* VENDOR_EDIT */
endif

include $(call my-dir)/config-$(FFMPEG_ARCH_VARIANT).mak
