#
# Makefile for the touchscreen drivers.
#
obj-$(CONFIG_TOUCHPANEL_OPPO) += util_interface/
obj-$(CONFIG_TOUCHPANEL_OPPO) += touchpanel_common_driver.o touchpanel_prevention.o touch.o
obj-$(CONFIG_TOUCHPANEL_ALGORITHM) += touchpanel_algorithm.o
obj-$(CONFIG_TOUCHPANEL_SAMSUNG) += Samsung/
